#' Plotting function for the hierarchical importance
#' 
#' This function takes the 4 column list generated by \code{ImportanceHie} and
#' plots the importance of each variable in each local classifier as either a
#' bubble plot or a heat map.
#' 
#' @author Yoni Gavish <gavishyoni@@gmail.com>
#' 
#' @param input.data           Data frame, data to be used for plotting.
#'   
#' @param X.data               The column number in \code{input.data} that
#'   contains the categories for the X axis.
#'   
#' @param Y.data               The column number in \code{input.data} that
#'   contains the categories for the Y axis.
#'   
#' @param imp.data             The column number in \code{input.data} that
#'   contains the variable importance values (or any other quantitative vector)
#'   that will scale the bubble size or tile colour.
#'   
#' @param plot.type            The type of plot to produce. Can be either
#'   \code{"Tile"} (default) \code{"Bubble"}.
#'   
#' @param imp.title            Character, title for the Importance legend. 
#' 
#' @param X.Title              Character, title for the x axis.
#' 
#' @param Y.Title              Character, title for the y axis.
#'   
#' @param low.col              Character, if \code{plot.type} is set to
#'   \code{"Tile"}, the colour to use for the lowest importance value.
#'   
#' @param high.col             Character, if \code{plot.type} is set to
#'   \code{"Tile"}, the colour to use for the highest importance value.
#'   
#' @param geom.tile.bor.col    Character, if \code{plot.type} is set to
#'   \code{"Tile"}, the colour to use for the border of tiles. Set to NA for no
#'   tile borders.
#'   
#' @param pos.col              Character, if \code{plot.type} is set to
#'   \code{"Bubble"}, the colour to use for importance values > 0.
#'   
#' @param zero.col             Character, if \code{plot.type} is set to
#'   \code{"Bubble"}, the colour to use for importance values = 0.
#'   
#' @param neg.col              Character, if \code{plot.type} is set to
#'   \code{"Bubble"}, the colour to use for importance values < 0.
#'   
#' @param supp.warn            Logical, if \code{TRUE}, warning will not be
#'   printed. Otherwise, the function may print warnings regarding deprecated
#'   factor levels.
#'   
#' @param \dots  Optional parameters to be passed to low level functions.
#' 
#' 
#' @details Based on the package \code{\link{ggplot2}}. The generated plot has
#'   the two categorical values as the X and Y axis. For each combination of X 
#'   and Y, the plot present the variable importance either as a heat map (when
#'   setting \code{plot.type = "Tile"}) or as a bubble plot (when setting
#'   \code{plot.type = "Bubble"}).
#'  @return The function returns a plot. If the function is returned to an 
#'    object, then the plot can be accessed and further edited using $plot on
#'    the new object (resulting with an object of class \code{ggplot}).
#'    
#' @seealso \code{\link{ImportanceHie}} for extracting importance values from an
#'   object of class \code{"HRF"}.
#'   
#' @examples
#' set.seed(354)
#' random.hRF <- RandomHRF(num.term.nodes = 20, tree.depth = 4)
#' train.data <- random.hRF$train.data
#'
#' hie.RF.random <- RunHRF(train.data = train.data, 
#'                         case.ID    = "case.ID", 
#'                         hie.levels = c(2:(random.hRF$call$tree.depth + 1)))
#'                         
#' Importance.hie.RF <- ImportanceHie(hie.RF     = hie.RF.random,
#'                                    format.out = c("col.4.out"))
#'                                    
#' PlotImportanceHie(input.data = Importance.hie.RF,
#'                   X.data     = 2,                                     
#'                   Y.data     = 3,                            
#'                   imp.data   = 4,
#'                   plot.type  = "Tile",
#'                   supp.warn  = FALSE) 
#'                     
#' # Tile, black and white
#' # label with the classifier.ID instead of the parent node name.
#' impor.plot.tile <- PlotImportanceHie(input.data        = Importance.hie.RF,
#'                                      X.data            = 1,                                    
#'                                      Y.data            = 3,                            
#'                                      imp.data          = 4,
#'                                      plot.type         = "Tile",
#'                                      low.col           = "white" ,                            
#'                                      high.col          = "black",
#'                                      geom.tile.bor.col = "gray20",
#'                                      supp.warn         = TRUE) 
#'                                       
#' # further editing of the plot with ggplot2
#' impor.plot.tile.2 <- impor.plot.tile$plot + 
#'                      theme(axis.title.y = element_text(size   = 20,
#'                                                        colour = "red"))
#' impor.plot.tile.2 <- impor.plot.tile.2 + 
#'    ggtitle("The mean decrease in accuracy of each 
#'    explanatory variable in each local classifier")
#' impor.plot.tile.2 
#' 
#' #Bubble
#' PlotImportanceHie(input.data = Importance.hie.RF,
#'                   X.data     = 2,                                    
#'                   Y.data     = 3,                            
#'                   imp.data   = 4,
#'                   plot.type  = "Bubble")
#'
#' #Bubble, black and white
#' PlotImportanceHie(input.data = Importance.hie.RF,
#'                   X.data     = 2,                                     
#'                   Y.data     = 3,                            
#'                   imp.data   = 4,
#'                   plot.type  = "Bubble",
#'                   pos.col    = "black",                                        
#'                   zero.col   = "gray50",                                         
#'                   neg.col    = "white") 
#'     
#' @export
#' 


# takes as input the list generated  by ImportanceHie
# usaes the four column format list with classifer name, parent name, variable name and importance as the four columns
# plots a n*k table, with n being the number of parent node (number of local classifers) and k being the number of explanatory variables
# for each combination of parent node and variable, a circle is ploted.
# the size of the circle represent the value ofmean decrease in accuracy
# the colour of the circles represent the sign of the mean decreaes in accuracy
# white - positive
# yellow - exactly zero
# light grey -  negative 

PlotImportanceHie = function(input.data,                                        # data frame containing the importance data, each row is for a specific combination of local classifer and explanatory variable. default format is assumed to be the 4 column format data frame of ImportanceHie
                             X.data    = 2,                                     # integer, the column number that contains yje data for the X axis
                             Y.data    = 3,                                     # integer, the column number that contains the data for the y axis
                             imp.data  = 4,                                     # the column number that contains the importance data for tthe tiles or bubbles
                             plot.type = "Tile",                                # Character, meaningfull values are "Tile" (default) or "Bubble", the type of plot that will be returned. "tile" returns a geom tile, with colur of the tiel representing the mean decrease in accuracy. 
                             imp.title = colnames(input.data)[imp.data],        # Character - the title to use for the Importance legend
                             X.Title   = colnames(input.data)[X.data],          # Character, title for the x axis
                             Y.Title   = colnames(input.data)[Y.data],          # Character, title for the y axis
                             low.col   = "blue" ,                               # Charcther, if type=='Tile', the colour to use for the highest importance value                 
                             high.col  = "red",                                 # Charcther, if type=='Tile', the colour to use for the lowest importance value    
                             geom.tile.bor.col = "white",                       # Charcther, the color for theif type=='Tile', the colour to use for the border of tiles. SEt to NA for no tile borders.
                             pos.col   = "green",                               # Charcther, if type=='Bubble', the colour to use for the  importance values >0          
                             zero.col  = "white",                               # Charcther, if type=='Bubble', the colour to use for the importance values ==0          
                             neg.col   = "red",                                 # Charcther, if type=='Bubble', the colour to use for the  importance value <0          
                             supp.warn = TRUE,                                  # Logical, if TRUe, than warnings will not be printed
                             ...)
{ # start the function
  
  #require(ggplot2)
  
  ################### 
  ## Arrange data  ##
  ###################
  
  
  # define the local environment
  localenv <- environment()
 
  # check plot.type
  if(plot.type != "Tile" && plot.type != "Bubble")
  { stop("\nplot.type can be either 'Tile' or 'Bubble'\n")}
  
  # create the work data according to users input
  work.data           <- input.data[, c(X.data,Y.data, imp.data)]
  colnames(work.data) <- c("X.var", "Y.var", "imp.var")
  
  # factor the x and y
  work.data$X.var <- suppressWarnings(factor(work.data$X.var, 
                            as.character(work.data$X.var)))
  
  work.data$Y.var <- suppressWarnings(factor(work.data$Y.var, 
                            as.character(work.data$Y.var)))

 ################################# 
 ## plot when plot.type=="Tile" ##
 #################################
 
   if(plot.type=="Tile")
   { p <- ggplot(work.data,
                 aes(X.var, Y.var),
                 environment = localenv) # without the environment argument, ggplot2 will look for work.data in the global environment
     p <- p + geom_tile(aes(fill = work.data$imp.var),
                        color = geom.tile.bor.col)
     p <- p + xlab(X.Title) 
     p <- p + ylab(Y.Title)  
     p <- p + scale_fill_continuous(low   = low.col, 
                                    high  = high.col,
                                    guide = "colourbar",
                                    guide_colourbar(title = imp.title))
   } # end plot "Tile"
 
 ################################### 
 ## plot when plot.type=="Bubble" ##
 ###################################
 
   if(plot.type=="Bubble")
   {
     # add the sign column
     for (k3 in 1:dim(work.data)[1])
       {
       if(work.data[k3, 3] >  0 ) {work.data[k3, 4] <- "Positive"}
       if(work.data[k3, 3] == 0 ) {work.data[k3, 4] <- "Zero"}
       if(work.data[k3, 3] <= 0 ) {work.data[k3, 4] <- "Negative"}
       }
     colnames(work.data)[4] <- "sign.imp"
     
     # create the colours vector for Scale_Fill_Manual
     fillScaleValues <- c( "Positive" = pos.col,
                           "Zero"     = zero.col,
                           "Negative" = neg.col )
     
     # start the ggplot
     p <- ggplot(work.data,aes(X.var, Y.var),
                 environment = localenv )
     p <- p + geom_point(aes(size = abs(work.data$imp.var),
                             fill = work.data$sign.imp),
                         shape=21)
     p <- p + xlab(X.Title) 
     p <- p + ylab(Y.Title)  
     p <- p + scale_size_continuous(guide = "legend",
                                    guide_legend(title = imp.title))
     p <- p + scale_fill_manual(values = fillScaleValues, 
                                name = "Sign")  
   } # end plot "Bubble"

 #############
 ## Return  ##
 ############# 
 #suppressWarnings(print(p)) 
#return(p)

if(supp.warn){return(suppressWarnings(print(p)))} else{return(print(p))}
  
} # end function Plot_Hie_Imp.R